services:
  temperature-monitor:
    command: /weather-station/entrypoint.sh
    container_name: temperature-monitor
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - PUID=568
      - PGID=568
      - USB_DEVICE_PATH=/dev/bus/usb
      - TZ=America/Los_Angeles
    build:
      context: .
    image: weather-station:local
    ports:
      - "8001:8000"
    restart: unless-stopped
    volumes:
      - /mnt/ssd/apps/weather-station:/weather-station
      - /etc/localtime:/etc/localtime:ro
